export const projects = [


    {
      title: 'Shop System',
      tagline: 'A shop website with income calculation, daily reports, and debt management.',
      description: 'A comprehensive shop management system that allows you to calculate total income and generate daily reports at the end of the day. The system also includes robust debt management functionality to track and manage outstanding payments.',
      techStack: ['MongoDB', 'Express', 'Node.js', 'React'],
      role: 'Full Stack Developer',
      status: 'Client Work',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/shop-system',
      image: '/project5.png',
    },
    {
      title: 'Weather Website',
      tagline: 'A weather website that fetches and displays weather data in a well-designed interface.',
      description: 'Project focused on developing a weather website that gets the city name from the user, fetches weather data from API, and displays the results in a well-designed and user-friendly way.',
      techStack: ['HTML', 'CSS', 'JavaScript'],
      role: 'Frontend Developer',
      status: 'Open Source',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/weather-website',
      image: '/project6.png',
    },
    {
      title: 'To-Do List',
      tagline: 'A task manager where you can add, complete, delete, and filter tasks by status.',
      description: 'I created a task manager / To-Do List where you can add tasks, mark them as completed and delete them, also view them according to their status with a clean and intuitive interface.',
      techStack: ['HTML', 'CSS', 'JavaScript'],
      role: 'Frontend Developer',
      status: 'Open Source',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/todo-list',
      image: '/project3.png',
    },
    {
      title: 'Social Media Dashboard',
      tagline: 'A dashboard that aggregates content from various social media platforms in one place.',
      description: 'I created and implemented a dashboard that aggregates content from various social media platforms. Users can login, connect their accounts and view their feeds in one centralized location.',
      techStack: ['HTML', 'CSS', 'JavaScript'],
      role: 'Frontend Developer',
      status: 'Client Work',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/social-media-dashboard',
      image: '/project4.png',
    },
    {
      title: 'Sales Management System',
      tagline: 'A web-based platform for managing customers, salesmen, invoices, and items.',
      description: 'The Sales Management System is a web-based platform for managing customers, salesmen, invoices, and items. It streamlines sales operations by tracking transactions, generating invoices, and maintaining inventory records. Designed to enhance efficiency, it helps businesses manage sales, reduce errors, and improve overall performance.',
      techStack: ['Next.js', 'Laravel', 'MariaDB', 'MySQL'],
      role: 'Full Stack Developer',
      status: 'Featured',
      liveDemo: 'https://sales-management-demo.vercel.app',
      github: 'https://github.com/obai-kaddour/sales-management-system',
      image: '/project7.jpg',
    },
    {
      title: 'Inventory Management',
      tagline: 'A multi-tenant inventory management system with comprehensive REST API.',
      description: 'A multi-tenant inventory management system built with Laravel 12, designed to help businesses manage their inventory, customers, suppliers, and business operations through a comprehensive REST API. The system supports multiple organizations operating independently with features like customer management, warehouse tracking, sales team management, and financial operations. Built with modern Laravel practices including multi-tenancy, audit trails, and subscription-based access control.',
      techStack: ['Next.js', 'Laravel', 'PostgreSQL'],
      role: 'Full Stack Developer',
      status: 'In Development',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/inventory-management',
      image: '/project9.png',
    },
      {
      title: 'Academic Registration',
      tagline: 'Full stack web application for University Academic Registration.',
      description: 'I designed and implemented a comprehensive full stack web application for University Academic Registration. This system provides a complete solution for managing student registrations, course enrollments, and academic records with a user-friendly interface and robust backend functionality.',
      techStack: ['HTML/CSS/JS', 'PHP', 'MySQL', 'MariaDB'],
      role: 'Full Stack Developer',
      status: 'Featured',
      liveDemo: '',
      github: 'https://github.com/obai-kaddour/academic-registration',
      image: '/project1.png',
    },
  ];

 